### ISSUE TITLE
When generating pods from files: CronJob labels are ignored

### ISSUE THREAD

**Issue by zivnevo** [IBM/network-config-analyzer#19]
A `CronJob` has one more level of nesting, compared to a `Job` - the `jobTemplate`.
The code currently doesn't treat this special case, but we also don't have a CronJob with labels in our test suite.
My guess is that if the CronJob defines a container with named ports, they will be ignored too.
A more realistic example:
```
 apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: tomtest
      labels:
        app: test
        tier: test
        tester: tom
    spec:
     schedule: "* * * * *"
     jobTemplate:
       metadata:
         name: tomtest-crons
       spec:
         template:
           metadata:
             labels:
                app: test
                tier: test
                tester: tom
                build_id: tom3
           containers:
             - name: cron
               image: giantswarm/tiny-tools
               imagePullPolicy: IfNotPresent
               env:
               - name: TOMTEST
                 value: "3"
               args:
               - /bin/sh
               - -c
               - date;echo hi;sleep 600;echo bye;date
             restartPolicy: Never
             resources:
               requests:
                 cpu: "1"
                 memory: "2G"
               limits:
                 cpu: "1"
                 memory: "2G"
```
