### ISSUE TITLE
Allow reading endpoints defined in a yaml file (not as a list)

### ISSUE THREAD

**Issue by zivnevo** [IBM/network-config-analyzer#208]
e.g. this file:
```yaml
# worker node 1
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  labels:
    ibm.role: worker_private
  name: worker1-worker-private
spec:
  node: node1
---
# worker node 2
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  labels:
    ibm.role: worker_private
  name: worker2-worker-private
spec:
  node: node2
```
