### ISSUE TITLE
A strange warning when parsing a service with two numeric ports

### ISSUE THREAD

**Issue by zivnevo** [IBM/network-config-analyzer#293]
When parsing the following service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  namespace: redis
  labels:
    app: redis
    role: follower
    tier: backend
spec:
  ports:
  - port: 6379
  - port: 5378
  selector:
    app: redis
    role: follower
    tier: backend
```
I get this error
```
Warning: The port  is not unique in Service redis-follower. Ignoring the port
```
but port numbers ARE unique.
