### ISSUE TITLE
Resource directories are always scanned recursively

### ISSUE THREAD

**Issue by zivnevo** [IBM/network-config-analyzer#316]
Consider this yaml
```yaml
resourceList: tests/istio_testcases
networkConfigList:
  - name: test
    networkPolicyList:
      - tests/istio_testcases/example_policies

queries:
  - name: test-query
    connectivityMap:
      - test
```

If ran from repository root, it actually finds resources, although the directories specified in `resourceList` and in `networkPolicyList` do not contain any. [Our specification](https://github.com/IBM/network-config-analyzer/blob/master/docs/SchemeFileFormat.md) says that to get a recursive scan, paths must end with `/**`.

The problem is probably in `DirScanner._scan_dir_for_yamls()`, as `os.walk` works recursively by default.
