### ISSUE TITLE
Inconsistency in the way live-sim works with scheme files

### ISSUE THREAD

**Issue by zivnevo** [IBM/network-config-analyzer#593]
When using a scheme file:
* If using a global `podList` or `resourceList` and not setting a network-config-specific `podList` or `resourceList` - live-sim doesn't work (in the log it seems as if `kube-dns` was added, but in practice it is not added).
* If a network-config-specific `podList` or `resourceList` is set, live-sim works as expected.

## Example
The two scheme files below produce different connectivity maps.
###  `test.scheme.yaml` - live-sim doesn't work
```yaml
resourceList: tests/k8s_testcases/example_policies/online_boutique/new_online_boutique_manifests
networkConfigList:
  - name: test
    networkPolicyList:
      - tests/k8s_testcases/example_policies/online_boutique/synthesis_res_new_online_boutique.yaml

queries:
  - name: test-query
    connectivityMap:
      - test
```
###  `test2.scheme.yaml` - live-sim works
```yaml
resourceList: tests/k8s_testcases/example_policies/online_boutique/new_online_boutique_manifests
networkConfigList:
  - name: test
    resourceList: tests/k8s_testcases/example_policies/online_boutique/new_online_boutique_manifests
    networkPolicyList:
      - tests/k8s_testcases/example_policies/online_boutique/synthesis_res_new_online_boutique.yaml

queries:
  - name: test-query
    connectivityMap:
      - test
```
