### ISSUE TITLE
Inconsistencies resource loading in scheme file

### ISSUE THREAD

**Issue by tanyaveksler** [IBM/network-config-analyzer#660]
Look in `tests/istio_testcases/example_policies/online_boutique_multi_layer_from_live_cluster_test`:
When moving `sidecars.yaml` resource from `networkPolicyList` to `resourceList`, this resource is not loaded.
However, when moving also rest of policy resources from `networkPolicyList` to `resourceList` (see below), the sidecars are loaded:

```
resourceList: onlineboutique-resources/

networkConfigList:
  - name: onlineboutique-resources
    resourceList:
      - onlineboutique-resources/
      - istio-gateways.yaml
      - network_policies.yaml
      - sidecars.yaml
    networkPolicyList:
#      - istio-gateways.yaml
#      - network_policies.yaml
#      - sidecars.yaml

```
